/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter (void);
GtkWidget* create_Affichage (void);
GtkWidget* create_modifier (void);
GtkWidget* create_mainwindow (void);
GtkWidget* create_login (void);
GtkWidget* create_gestion_election (void);
GtkWidget* create_ajouter_election (void);
GtkWidget* create_modifier_election (void);
GtkWidget* create_Gestion__de_bureux_de_vote (void);
GtkWidget* create_ajout_du_bureau_de_vote (void);
GtkWidget* create_modification_du_bureau_de_vote (void);
GtkWidget* create_supprimer_election (void);
GtkWidget* create_espace_electeur (void);
GtkWidget* create_gestion_de_vote (void);
GtkWidget* create_gestion_liste_electorale (void);
GtkWidget* create_ajout_liste_electorale (void);
GtkWidget* create_supprimer_compte (void);
GtkWidget* create_confiramtion_supp (void);
GtkWidget* create_confirmer_ajout (void);
GtkWidget* create_confirmation_ajout (void);
