/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajouter;
  GtkWidget *Affichage;
  GtkWidget *modifier;
  GtkWidget *mainwindow;
  GtkWidget *login;
  GtkWidget *gestion_election;
  GtkWidget *ajouter_election;
  GtkWidget *modifier_election;
  GtkWidget *Gestion__de_bureux_de_vote;
  GtkWidget *ajout_du_bureau_de_vote;
  GtkWidget *modification_du_bureau_de_vote;
  GtkWidget *supprimer_election;
  GtkWidget *espace_electeur;
  GtkWidget *gestion_de_vote;
  GtkWidget *gestion_liste_electorale;
  GtkWidget *ajout_liste_electorale;
  GtkWidget *supprimer_compte;
  GtkWidget *confiramtion_supp;
  GtkWidget *confirmer_ajout;
  GtkWidget *confirmation_ajout;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ajouter = create_ajouter ();
  gtk_widget_show (ajouter);
  Affichage = create_Affichage ();
  gtk_widget_show (Affichage);
  modifier = create_modifier ();
  gtk_widget_show (modifier);
  mainwindow = create_mainwindow ();
  gtk_widget_show (mainwindow);
  login = create_login ();
  gtk_widget_show (login);
  gestion_election = create_gestion_election ();
  gtk_widget_show (gestion_election);
  ajouter_election = create_ajouter_election ();
  gtk_widget_show (ajouter_election);
  modifier_election = create_modifier_election ();
  gtk_widget_show (modifier_election);
  Gestion__de_bureux_de_vote = create_Gestion__de_bureux_de_vote ();
  gtk_widget_show (Gestion__de_bureux_de_vote);
  ajout_du_bureau_de_vote = create_ajout_du_bureau_de_vote ();
  gtk_widget_show (ajout_du_bureau_de_vote);
  modification_du_bureau_de_vote = create_modification_du_bureau_de_vote ();
  gtk_widget_show (modification_du_bureau_de_vote);
  supprimer_election = create_supprimer_election ();
  gtk_widget_show (supprimer_election);
  espace_electeur = create_espace_electeur ();
  gtk_widget_show (espace_electeur);
  gestion_de_vote = create_gestion_de_vote ();
  gtk_widget_show (gestion_de_vote);
  gestion_liste_electorale = create_gestion_liste_electorale ();
  gtk_widget_show (gestion_liste_electorale);
  ajout_liste_electorale = create_ajout_liste_electorale ();
  gtk_widget_show (ajout_liste_electorale);
  supprimer_compte = create_supprimer_compte ();
  gtk_widget_show (supprimer_compte);
  confiramtion_supp = create_confiramtion_supp ();
  gtk_widget_show (confiramtion_supp);
  confirmer_ajout = create_confirmer_ajout ();
  gtk_widget_show (confirmer_ajout);
  confirmation_ajout = create_confirmation_ajout ();
  gtk_widget_show (confirmation_ajout);

  gtk_main ();
  return 0;
}

